#!/usr/bin/bash

if [ "$(id -u)" != "0" ]; then
    echo "Run as root."
    exit 1
fi

docker-compose stop

echo "Remove all containers"
docker ps -a --format={{.ID}} | awk '{print $1}' | xargs docker rm -f

echo "Remove untagged images"
docker rmi $(sudo docker images | grep "^<none>" | awk '{print $3}')
