etcd:
  image: quay.io/coreos/etcd:v2.2.0
  net: "host"

master:
  image: gcr.io/google_containers/hyperkube:v1.0.6
  net: "host"
  # privileged: true
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    # Taken from
    # https://github.com/kubernetes/kubernetes/blob/master/docs/getting-started-guides/docker-multinode/worker.sh
    # - /:/rootfs:ro
    # - /sys:/sys:ro
    # - /dev:/dev
    # - /var/lib/docker/:/var/lib/docker:ro
    # - /var/lib/kubelet/:/var/lib/kubelet:rw
    # - /var/run:/var/run:rw
  command: /hyperkube kubelet --containerized --hostname-override="127.0.0.1" --address="0.0.0.0" --api-servers=http://localhost:8080 --config=/etc/kubernetes/manifests

proxy:
  image: gcr.io/google_containers/hyperkube:v1.0.6
  net: "host"
  privileged: true
  command: /hyperkube proxy --master=http://127.0.0.1:8080 --v=2
