data:
  image: tianon/true
  volumes:
    - /home/pablo/docker_volumes/data:/opt/data

etcd:
  image: quay.io/coreos/etcd:v2.2.0
  net: "host"

master:
  image: gcr.io/google_containers/hyperkube:v0.21.2
  net: "host"
  volumes_from:
    - data
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  command: /hyperkube kubelet --api_servers=http://localhost:8080 --v=2 --address=0.0.0.0 --enable_server --hostname_override=127.0.0.1 --config=/etc/kubernetes/manifests

proxy:
  image: gcr.io/google_containers/hyperkube:v0.21.2
  net: "host"
  privileged: true
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  command: /hyperkube proxy --master=http://127.0.0.1:8080 --v=2
