apiVersion: v1
kind: Service
metadata:
  name: data-ws
  labels:
    name: data-ws-service
spec:
  clusterIP: 10.0.0.113
  ports:
    - port: 8999
      name: api
  selector:
    app: data
    component: data-ws
