apiVersion: v1
kind: Service
metadata:
  name: data-notifier
  labels:
    name: data-notifier-service
spec:
  ports:
    - port: 8999
      name: api
  selector:
    app: data
    component: data-notifier
