apiVersion: v1
kind: Service
metadata:
  name: influxdb
  labels:
    name: influxdb-service
spec:
  clusterIP: 10.0.0.111
  ports:
    - port: 8086
      name: "api"
    - port: 8083
      name: "management"
  selector:
    app: data
    component: influxdb
