apiVersion: v1
kind: Service
metadata:
  name: rethinkdb
  labels:
    name: rethinkdb-service
spec:
  ports:
    - port: 29015
      name: "intracluster"
    - port: 28015
      name: "driver"
    - port: 8080
      name: "management"
  selector:
    app: data
    component: rethinkdb
