apiVersion: v1
kind: Pod
metadata:
  name: data-pipeline
  labels:
    app: data
spec:
  containers:
  - name: data-collector
    image: data-collector
  - name: data-processor
    image: data-processor
