apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: data-pipeline
  name: data-pipeline-controller
spec:
  replicas: 1
  selector:
    component: data-pipeline
  template:
    metadata:
      labels:
        app: data
        component: data-pipeline
    spec:
      containers:
        - name: data-collector
          image: data-collector
        - name: data-processor
          image: data-processor
