apiVersion: v1
kind: ReplicationController
metadata:
  name: influxdb
  labels:
    name: influxdb-rc
spec:
  replicas: 1
  selector:
    component: influxdb
  template:
    metadata:
      labels:
        app: data
        component: influxdb
    spec:
      containers:
        - image: tutum/influxdb
          name: influxdb
          ports:
            - containerPort: 8086
              name: "api"
            - containerPort: 8083
              name: "management"
          resources:
            limits:
              cpu: 100m
