apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    name: rabbitmq-service
spec:
  ports:
    - port: 5672
      name: "node"
    - port: 15672
      name: "management"
  selector:
    app: data
    component: rabbitmq
