apiVersion: v1
kind: Pod
metadata:
  labels:
    app: data
    etcd_node: etcd1
  name: etcd1
spec:
  containers:
  - command:
    - /etcd
    - -name
    - etcd1
    - -initial-advertise-peer-urls
    - "http://$(ETCD1_SERVICE_HOST):2380"
    - -listen-peer-urls
    - http://0.0.0.0:2380
    - -listen-client-urls
    - http://0.0.0.0:2379
    - -advertise-client-urls
    - "http://$(ETCD1_SERVICE_HOST):2379"
    - -initial-cluster
    - "etcd0=http://$(ETCD0_SERVICE_HOST):2380,etcd1=http://$(ETCD1_SERVICE_HOST):2380,etcd2=http://$(ETCD2_SERVICE_HOST):2380"
    - -initial-cluster-state
    - new
    image: quay.io/coreos/etcd:latest
    name: etcd1
    ports:
    - containerPort: 2379
      name: client
      protocol: TCP
    - containerPort: 2380
      name: server
      protocol: TCP
  restartPolicy: Never
