apiVersion: v1
kind: ReplicationController
metadata:
  name: data-pipeline
  labels:
    name: data-pipeline-rc
spec:
  replicas: 1
  selector:
    component: data-pipeline
  template:
    metadata:
      labels:
        app: data
        component: data-pipeline
    spec:
      containers:
        - name: data-collector
          image: data-collector
          volumeMounts:
            - mountPath: /opt/data
              name: data-storage
        - name: data-processor
          image: data-processor
          env:
            - name: RUST_LOG
              value: debug
          volumeMounts:
            - mountPath: /opt/data
              name: data-storage
      volumes:
        - emptyDir: {}
          name: data-storage
