apiVersion: v1
kind: ReplicationController
metadata:
  name: data-frontend
  labels:
    name: data-frontend-rc
spec:
  replicas: 1
  selector:
    component: data-frontend
  template:
    metadata:
      labels:
        app: data
        component: data-frontend
    spec:
      hostNetwork: true
      containers:
        - name: data-frontend
          image: data-frontend
          ports:
          - name: static
            containerPort: 80
