apiVersion: v1
kind: ReplicationController
metadata:
  name: data-collector
  labels:
    name: data-collector-rc
spec:
  replicas: 1
  selector:
    component: data-collector
  template:
    metadata:
      labels:
        app: data
        component: data-collector
    spec:
      hostNetwork: true
      containers:
        - name: data-collector
          image: data-collector
          volumeMounts:
            - mountPath: /opt/data/processor/queue
              name: data-storage
      volumes:
        - name: data-storage
          hostPath:
            path: /home/pablo/Desktop/tmp/collected
