apiVersion: v1
kind: ReplicationController
metadata:
  name: data-processor
  labels:
    name: data-processor-rc
spec:
  replicas: 1
  selector:
    component: data-processor
  template:
    metadata:
      labels:
        app: data
        component: data-processor
    spec:
      containers:
        - name: data-processor
          image: data-processor
          env:
            - name: RUST_LOG
              value: debug
          volumeMounts:
            - mountPath: /opt/data/processor/queue
              name: data-storage
              readOnly: true
      volumes:
        - name: data-storage
          hostPath:
            path: /home/pablo/Desktop/tmp/collected
