apiVersion: v1
kind: ReplicationController
metadata:
  name: data-backend
  labels:
    name: data-backend-rc
spec:
  replicas: 1
  selector:
    component: data-backend
  template:
    metadata:
      labels:
        app: data
        component: data-backend
    spec:
      containers:
        - image: data-backend
          name: data-backend
          ports:
            - containerPort: 80
              hostPort: 18000
              name: api
          resources:
            limits:
              cpu: 100m
