apiVersion: v1
kind: ReplicationController
metadata:
  name: rabbitmq
  labels:
    name: rabbitmq-rc
spec:
  replicas: 1
  selector:
    component: rabbitmq
  template:
    metadata:
      labels:
        app: data
        component: rabbitmq
    spec:
      containers:
      - image: rabbitmq:3-management
        name: rabbitmq
        ports:
          - containerPort: 5672
            name: "node"
          - containerPort: 15672
            name: "management"
        resources:
          limits:
            cpu: 100m
